### ISSUE TITLE
Fail to create a Flask project

### ISSUE THREAD

**Issue by romandueck** [romainberger/yeoman-flask#32]
user@notebook:~/projects/flask_project$ yo flask
/home/user/.npm-packages/lib/node_modules/generator-flask/app/index.js:17
util.inherits(Generator, yeoman.generators.NamedBase)
                                          ^

TypeError: Cannot read property 'NamedBase' of undefined
    at Object.<anonymous> (/home/user/.npm-packages/lib/node_modules/generator-flask/app/index.js:17:43)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as flask:app] (/home/user/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/home/user/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/home/user/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:262:16)
user@notebook:~/projects/flask_project$

**Comment by emilwall** [comment]
I'm also having this problem, with latest versions of node, npm, etc.

**Comment by ematta** [comment]
+1

**Comment by peratik** [comment]
```
TypeError: Cannot read property 'NamedBase' of undefined
    at Object.<anonymous> (C:\Users\Peratik\AppData\Roaming\npm\node_modules\generator-flask\app\index.js:17:44)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.get [as flask:app] (C:\Users\Peratik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:38:27)
    at Store.get (C:\Users\Peratik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:61:39)
```

**Comment by fureigh** [comment]
I'm encountering this problem too. In case the difference in line numbers is useful:

```
readline.js:982
            throw err;=================
            ^

TypeError: Cannot read property 'NamedBase' of undefined
    at Object.<anonymous> (/[HOME]/.nvm/versions/node/v6.7.0/lib/node_modules/generator-flask/app/index.js:17:43)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.get [as flask:app] (/[HOME]/.nvm/versions/node/v6.7.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
    at Store.get (/[HOME]/.nvm/versions/node/v6.7.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:61:39)
```

**Comment by kusnandartoni** [comment]
+1
same problem when generate flask
