### ISSUE TITLE
Error when start yo flask

### ISSUE THREAD

**Issue by suenot** [romainberger/yeoman-flask#9]
```
thatmean@thatmean-pc:~/Dropbox/sites/yo-flask$ yo flask

TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (/home/thatmean/.nvm/v0.10.6/lib/node_modules/generator-flask/node_modules/yeoman-generator/lib/util/common.js:5:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/thatmean/.nvm/v0.10.6/lib/node_modules/generator-flask/node_modules/yeoman-generator/lib/base.js:91:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

I use ubuntu 12.04 lts, node 0.10.6 installed with nvm, yeoman 1.0.4, python 2.7.3, pip 1.0.

**Comment by romainberger** [comment]
I've published a patch that should fix it. Can you please tell me if it's working? I don't have the same error so I can't be sure.

**Comment by suenot** [comment]
Problem is resolved.
